spring.application.name=blogapi
# Database connection URL
spring.datasource.url=jdbc:mysql://localhost:3306/blog_db

# Database username
spring.datasource.username=root

# Database password
spring.datasource.password=Beba2107

# Automatically update database tables based on entities
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in console
spring.jpa.show-sql=true

# MySQL driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver